// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// l1partition
NumericVector l1partition(NumericVector x, double epsilon, double ratio, long seed);
RcppExport SEXP VerificationMeasures_l1partition(SEXP xSEXP, SEXP epsilonSEXP, SEXP ratioSEXP, SEXP seedSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type epsilon(epsilonSEXP);
    Rcpp::traits::input_parameter< double >::type ratio(ratioSEXP);
    Rcpp::traits::input_parameter< long >::type seed(seedSEXP);
    __result = Rcpp::wrap(l1partition(x, epsilon, ratio, seed));
    return __result;
END_RCPP
}
// l1partition_approx
NumericVector l1partition_approx(NumericVector x, double epsilon, double ratio, long seed);
RcppExport SEXP VerificationMeasures_l1partition_approx(SEXP xSEXP, SEXP epsilonSEXP, SEXP ratioSEXP, SEXP seedSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type epsilon(epsilonSEXP);
    Rcpp::traits::input_parameter< double >::type ratio(ratioSEXP);
    Rcpp::traits::input_parameter< long >::type seed(seedSEXP);
    __result = Rcpp::wrap(l1partition_approx(x, epsilon, ratio, seed));
    return __result;
END_RCPP
}
