# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

l1partition <- function(x, epsilon, ratio, seed) {
    .Call('VerificationMeasures_l1partition', PACKAGE = 'VerificationMeasures', x, epsilon, ratio, seed)
}

l1partition_approx <- function(x, epsilon, ratio, seed) {
    .Call('VerificationMeasures_l1partition_approx', PACKAGE = 'VerificationMeasures', x, epsilon, ratio, seed)
}

